version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "4000:3000"
    volumes:
      - /app/node_modules
      - .:/app

  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #   - "4000:3000"
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run", "test"] # this command overrides the last one from Dockerfile

    # so to RUN TESTS:
    # - run second service as above
    # - (easier) attach to existing "web" service's bash and run `npm run test` manually from there
    #   - docker exec -it f1657de9eb8a sh


# to RUN this docker-compose file:
# - docker-compose up --build